[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "scipy>=1.16.1",
    "streamlit>=1.47.1",
]
